FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y curl make g++ ffmpeg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY package*.json ./
RUN npm install --omit=dev

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN mkdir -p /app/keys

EXPOSE 5050

CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]
